name: ${project.name}
version: ${project.version}
main: ${main.class}
description: ${project.description}
author: BukkitSmurf
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
api-version: 1.13
commands:
  lpc:
    description: Reload the configuration.
    permission: lpc.reload
    usage: "Usage: /lpc reload"