name: ${project.name}
version: ${project.version}
main: ${main.class}
description: ${project.description}
author: OnCode9
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
api-version: 1.13

commands:
  lpc:
    description: Reloads the configuration file.
    permission: lpc.reload
    usage: "Usage: /lpc reload"